apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-operator-crds/application.yaml
- prometheus/application.yaml
- prometheus-node-exporter/application.yaml
- grafana/dashboards/argo-cd.yaml
